name: PROS Project CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.6
    - name: Pip Installer
      uses: BSFishy/pip-action@v1
      with:
        packages: https://github.com/purduesigbots/pros-cli/releases/download/3.1.4/pros_cli_v5-3.1.4-py3-none-any.whl
    - name: Testing PROS Install 
      run: prosv5 --version
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Submodule Checkout
      uses: jwsi/submodule-checkout@v1
      with:
        ssh-key: '${{ secrets.DEPLOY_KEY }}'
    - name: make  
      run: prosv5 make clean all
